In [31]:
import pandas as pd
import numpy as np

from itertools import combinations #trabaja con strings
from math import comb #trabaja con numeros

2. Cargar el dataset

In [32]:
ruta = ("../data/raw/dataset_7variables_2000_2022.csv")
df = pd.read_csv(ruta)

3. Explorar datos

In [33]:
df.info

<bound method DataFrame.info of            entity  year  population     births    deaths  \
0     Afghanistan  2002  21378123.0  1015202.0  239161.0
1     Afghanistan  2003  22733053.0  1069727.0  243573.0
2     Afghanistan  2004  23560656.0  1095372.0  244435.0
3     Afghanistan  2005  24404575.0  1097038.0  241932.0
4     Afghanistan  2006  25424100.0  1120880.0  245586.0
...           ...   ...         ...        ...       ...
4239     Zimbabwe  2018  15034457.0   470991.0  125092.0
4240     Zimbabwe  2019  15271377.0   475267.0  126468.0
4241     Zimbabwe  2020  15526887.0   481152.0  126365.0
4242     Zimbabwe  2021  15797220.0   488642.0  138738.0
4243     Zimbabwe  2022  16069061.0   496240.0  124995.0

      child_deaths_under_5  health_percentage        gdp  life_expectancy
0                   123215           9.443391  1774.3087          56.2251
1                   123894           8.941258  1815.9282          57.1713
2                   122315           9.808474  1776.9182          57.8098
3                   118420           9.948289  1908.1147          58.2468
4                   116622          10.622766  1929.7239          58.5533
...                    ...                ...        ...              ...
4239                 25211           4.673280  5415.4930          60.9055
4240                 24647           3.232681  4993.8650          61.0603
4241                 23828           2.954401  4527.7393          61.5300
4242                 23391           2.671119  4827.1094          60.1347
4243                 23249           3.395195  5036.7830          62.3601

[4244 rows x 9 columns]>

In [34]:
df.columns.to_list()

['entity',
 'year',
 'population',
 'births',
 'deaths',
 'child_deaths_under_5',
 'health_percentage',
 'gdp',
 'life_expectancy']

In [35]:
df.isnull().sum()

entity                  0
year                    0
population              0
births                  0
deaths                  0
child_deaths_under_5    0
health_percentage       0
gdp                     0
life_expectancy         0
dtype: int64

4. Seleccionar variables

In [36]:
variables_numericas = ["population", 
                       "births", 
                       "deaths", 
                       "child_deaths_under_5", 
                       "health_percentage", 
                       "gdp", 
                       "life_expectancy"]
df_vn = df[variables_numericas].copy()
df_vn.head(5)

,population,births,deaths,child_deaths_under_5,health_percentage,gdp,life_expectancy
0,21378123.0,1015202.0,239161.0,123215,9.443391,1774.3087,56.2251
1,22733053.0,1069727.0,243573.0,123894,8.941258,1815.9282,57.1713
2,23560656.0,1095372.0,244435.0,122315,9.808474,1776.9182,57.8098
3,24404575.0,1097038.0,241932.0,118420,9.948289,1908.1147,58.2468
4,25424100.0,1120880.0,245586.0,116622,10.622766,1929.7239,58.5533

In [37]:
n = len(variables_numericas)
total_combinaciones = comb(n,2) #quiero hacer combinaciones de a 2
print(f"Número de combinaciones: {total_combinaciones}")

Número de combinaciones: 21

In [41]:
#Inicializamos el arreglo para guardar los resultados
resultados = []

for variable_x, variable_y in combinations(variables_numericas, 2):
    #se calcula r mediante la funcion corr de pandas
    r = df_vn[variable_x].corr(df_vn[variable_y], method="pearson")

    #se guardan en un arreglo todos los valores obtenidos
    resultados.append([variable_x, variable_y, r, abs(r)])

#El arreglo de resultados se transforma en df de pandas para manipularlo
#Convertir los resultados en un DataFrame
df_resultados = pd.DataFrame(
    resultados, 
    columns=["Variable X", "Variable Y", "Pearson", "Intensidad"]) #intensidad es el valor ABSOLUTO de r

#Ordenar por intensidad de mayor a menor
df_resultados = df_resultados.sort_values(
    by="Intensidad", #esta es la variable por la cual se ordena
    ascending= False).reset_index(drop=True) #drop = True evita que le indice original se aregue como una columna adicional

display(df_resultados)

              Variable X            Variable Y   Pearson  Intensidad
0             population                deaths  0.997836    0.997836
1                 births                deaths  0.993034    0.993034
2             population                births  0.992562    0.992562
3                 births  child_deaths_under_5  0.967222    0.967222
4                 deaths  child_deaths_under_5  0.944894    0.944894
5             population  child_deaths_under_5  0.935124    0.935124
6                    gdp       life_expectancy  0.675566    0.675566
7      health_percentage       life_expectancy  0.286925    0.286925
8      health_percentage                   gdp  0.193442    0.193442
9   child_deaths_under_5       life_expectancy -0.067931    0.067931
10  child_deaths_under_5                   gdp -0.062524    0.062524
11  child_deaths_under_5     health_percentage -0.049833    0.049833
12                births                   gdp -0.044742    0.044742
13                births     health_percentage -0.030696    0.030696
14            population                   gdp -0.030289    0.030289
15                deaths                   gdp -0.028315    0.028315
16                births       life_expectancy -0.019662    0.019662
17            population     health_percentage -0.016296    0.016296
18                deaths     health_percentage -0.012450    0.012450
19            population       life_expectancy  0.006890    0.006890
20                deaths       life_expectancy -0.001312    0.001312