# Practica 1
## Analisis de la evolución población mundial
### Actividad 1- identificaión de la fuente

**Cita**
>UN, World Population Prospects (2024) – processed by Our World in Data. “Annual change in population – UN WPP” [dataset]. United Nations, “World Population Prospects”; United Nations, “World Population Prospects - Interim Update” [original data].

**Preguntas**

Responde brevemente: 

1.¿Quién produjo originalmente los datos? United Nations

2.¿Qué organización los procesa para su utilización en Our World in Data? Our World in Data

3.¿Qué representa la variable que analizarás? Annual population growth

In [6]:
import pandas as pd
import numpy as np

df = pd.read_csv(r'C:\5to Semestre\BigData\U1_1_Probabilidad_estadistica\data\raw\annual-population-growth\annual-population-growth.csv')
df

,Entity,Code,Year,Annual change in population,Annual population change (Projected)
0,Afghanistan,AFG,1951,103163.0,NaN
1,Afghanistan,AFG,1952,108441.0,NaN
2,Afghanistan,AFG,1953,108919.0,NaN
3,Afghanistan,AFG,1954,111251.0,NaN
4,Afghanistan,AFG,1955,119027.0,NaN
...,...,...,...,...,...
38395,Zimbabwe,ZWE,2096,NaN,100752.0
38396,Zimbabwe,ZWE,2097,NaN,91796.0
38397,Zimbabwe,ZWE,2098,NaN,87605.0
38398,Zimbabwe,ZWE,2099,NaN,76670.0
38399,Zimbabwe,ZWE,2100,NaN,70019.0

In [ ]:
df.head(3)

,Entity,Code,Year,Annual change in population,Annual population change (Projected)
0,Afghanistan,AFG,1951,103163.0,NaN
1,Afghanistan,AFG,1952,108441.0,NaN
2,Afghanistan,AFG,1953,108919.0,NaN

In [2]:
df.isnull().sum()

Entity                                      0
Code                                     1200
Year                                        0
Annual change in population             19712
Annual population change (Projected)    18688
dtype: int64

In [ ]:
df["Entity"].nunique()

256

In [ ]:
df_extraccion_entity = df[["Entity", "Year"]]
df_extraccion_entity.head(3)

        Entity  Year
0  Afghanistan  1951
1  Afghanistan  1952
2  Afghanistan  1953

In [ ]:
df_2020 = df[df["Year"] == 2020]
df_2020.head(3)

,Entity,Code,Year,Annual change in population,Annual population change (Projected)
69,Afghanistan,AFG,2020,1212852.0,NaN
219,Africa (UN),UN_AFR,2020,32815675.0,NaN
369,Albania,ALB,2020,-13061.0,NaN

In [ ]:
df_2020_ext_col1 = df_2020[["Entity","Year"]]
df_2020_ext_col1.head(3)
df_2020_ext_col2 = df[df["Year"] == 2020][["Entity", "Year"]]
df_2020_ext_col2.head(3)

          Entity  Year
69   Afghanistan  2020
219  Africa (UN)  2020
369      Albania  2020

In [26]:
df_2005_2020 = df[(df["Year"] >= 2005) & (df["Year"] <= 2020) & (df["Entity"] == "Mexico")]
df_2005_2020.head()

,Entity,Code,Year,Annual change in population,Annual population change (Projected)
22254,Mexico,MEX,2005,1417373.0,NaN
22255,Mexico,MEX,2006,1442162.0,NaN
22256,Mexico,MEX,2007,1520690.0,NaN
22257,Mexico,MEX,2008,1599930.0,NaN
22258,Mexico,MEX,2009,1625434.0,NaN

In [ ]:
df_ext_entiAnual = df_2005_2020[["Entity", "Annual change in population"]]
df_ext_entiAnual

       Entity  Annual change in population
22254  Mexico                    1417373.0
22255  Mexico                    1442162.0
22256  Mexico                    1520690.0
22257  Mexico                    1599930.0
22258  Mexico                    1625434.0
22259  Mexico                    1624178.0
22260  Mexico                    1619605.0
22261  Mexico                    1574705.0
22262  Mexico                    1525364.0
22263  Mexico                    1440693.0
22264  Mexico                    1288045.0
22265  Mexico                    1179034.0
22266  Mexico                    1148708.0
22267  Mexico                    1173661.0
22268  Mexico                    1189265.0
22269  Mexico                    1036075.0

In [2]:
df_ext_entiAnual.mean(numeric_only=True)

NameError: name 'df_ext_entiAnual' is not defined

In [ ]:
df["Entity"].nunique()

256

In [21]:
df_n = df[df["Entity"].str.startswith("R")]
df_n

,Entity,Code,Year,Annual change in population,Annual population change (Projected)
28200,Reunion,REU,1951,9292.0,NaN
28201,Reunion,REU,1952,9677.0,NaN
28202,Reunion,REU,1953,10116.0,NaN
28203,Reunion,REU,1954,10829.0,NaN
28204,Reunion,REU,1955,11294.0,NaN
...,...,...,...,...,...
28795,Rwanda,RWA,2096,NaN,107685.0
28796,Rwanda,RWA,2097,NaN,79080.0
28797,Rwanda,RWA,2098,NaN,76750.0
28798,Rwanda,RWA,2099,NaN,91618.0
28799,Rwanda,RWA,2100,NaN,87308.0

In [9]:
df_1983_2021 = df[(df["Year"] >= 1983) & (df["Year"] <= 2021) & (df["Entity"] == "Rwanda")]
df_1983_2021

,Entity,Code,Year,Annual change in population,Annual population change (Projected)
28682,Rwanda,RWA,1983,193756.0,NaN
28683,Rwanda,RWA,1984,202317.0,NaN
28684,Rwanda,RWA,1985,209602.0,NaN
28685,Rwanda,RWA,1986,214657.0,NaN
28686,Rwanda,RWA,1987,217607.0,NaN
28687,Rwanda,RWA,1988,218581.0,NaN
28688,Rwanda,RWA,1989,216634.0,NaN
28689,Rwanda,RWA,1990,190604.0,NaN
28690,Rwanda,RWA,1991,151651.0,NaN
28691,Rwanda,RWA,1992,156302.0,NaN
28692,Rwanda,RWA,1993,297876.0,NaN
28693,Rwanda,RWA,1994,-1188784.0,NaN
28694,Rwanda,RWA,1995,-1118240.0,NaN
28695,Rwanda,RWA,1996,1034649.0,NaN
28696,Rwanda,RWA,1997,1046470.0,NaN
28697,Rwanda,RWA,1998,326451.0,NaN
28698,Rwanda,RWA,1999,66229.0,NaN
28699,Rwanda,RWA,2000,66019.0,NaN
28700,Rwanda,RWA,2001,73155.0,NaN
28701,Rwanda,RWA,2002,113094.0,NaN
28702,Rwanda,RWA,2003,186693.0,NaN
28703,Rwanda,RWA,2004,229971.0,NaN
28704,Rwanda,RWA,2005,237683.0,NaN
28705,Rwanda,RWA,2006,244719.0,NaN
28706,Rwanda,RWA,2007,250689.0,NaN
28707,Rwanda,RWA,2008,254328.0,NaN
28708,Rwanda,RWA,2009,256170.0,NaN
28709,Rwanda,RWA,2010,257122.0,NaN
28710,Rwanda,RWA,2011,256182.0,NaN
28711,Rwanda,RWA,2012,256162.0,NaN
28712,Rwanda,RWA,2013,263436.0,NaN
28713,Rwanda,RWA,2014,271418.0,NaN
28714,Rwanda,RWA,2015,275268.0,NaN
28715,Rwanda,RWA,2016,279157.0,NaN
28716,Rwanda,RWA,2017,282879.0,NaN
28717,Rwanda,RWA,2018,285938.0,NaN
28718,Rwanda,RWA,2019,288102.0,NaN
28719,Rwanda,RWA,2020,289736.0,NaN
28720,Rwanda,RWA,2021,289422.0,NaN

In [10]:
df_1983_2021.mean(numeric_only=True)

Year                                      2002.000000
Annual change in population             195992.435897
Annual population change (Projected)              NaN
dtype: float64

In [11]:
df_1983_2021.median(numeric_only=True)

Year                                      2002.0
Annual change in population             244719.0
Annual population change (Projected)         NaN
dtype: float64

In [12]:
df_1983_2021.var(numeric_only=True)

Year                                    1.300000e+02
Annual change in population             1.381985e+11
Annual population change (Projected)             NaN
dtype: float64

In [13]:
df_1983_2021.std(numeric_only=True)

Year                                        11.401754
Annual change in population             371750.603383
Annual population change (Projected)              NaN
dtype: float64

In [14]:
df_1983_2021.min(numeric_only=True)

Year                                       1983.0
Annual change in population            -1188784.0
Annual population change (Projected)          NaN
dtype: float64

In [15]:
df_1983_2021.max(numeric_only=True)

Year                                       2021.0
Annual change in population             1046470.0
Annual population change (Projected)          NaN
dtype: float64

In [34]:
df.loc[(df["Year"] == 2000) & (df["Entity"] == "Mexico")]

,Entity,Code,Year,Annual change in population,Annual population change (Projected)
22249,Mexico,MEX,2000,1509843.0,NaN